services:
  mysql:
    image: mysql:8.0
    container_name: travelagency-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: travelagency
      MYSQL_USER: traveluser
      MYSQL_PASSWORD: travel1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - travelagency-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: travelagency-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin2026
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
    command: start-dev --import-realm --hostname-strict=false
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm-export:/opt/keycloak/data/import
    networks:
      - travelagency-network

  backend1:
    image: vicentetapia07/travelagency-backend:latest
    container_name: travelagency-backend1
    environment:
      DB_USER: traveluser
      DB_PASSWORD: travel1234
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/travelagency
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://${SERVER_HOST}/realms/travelagency-realm
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/travelagency-realm/protocol/openid-connect/certs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - travelagency-network

  nginx-backend:
    image: nginx:alpine
    container_name: travelagency-nginx-backend
    volumes:
      - ./nginx-backend-cloud.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
    networks:
      - travelagency-network

  frontend:
    image: vicentetapia07/travelagency-frontend:latest
    container_name: travelagency-frontend
    depends_on:
      - nginx-backend
    networks:
      - travelagency-network

  ssl-proxy:
    image: nginx:alpine
    container_name: travelagency-ssl
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - /home/ec2-user/certs:/etc/nginx/certs
    ports:
      - "443:443"
    depends_on:
      - frontend
      - keycloak
    networks:
      - travelagency-network

networks:
  travelagency-network:
    driver: bridge

volumes:
  mysql_data:
  keycloak_data:
