upstream backend {
    # Round-robin: distribuye las peticiones entre las 3 réplicas
    server backend1:8090;
    server backend2:8090;
    server backend3:8090;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
