server {
    listen 80;

    location /realms/ {
        proxy_pass http://travelagency-keycloak:8080/realms/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
    }

    location /resources/ {
        proxy_pass http://travelagency-keycloak:8080/resources/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://travelagency-nginx-backend:80/api/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://travelagency-frontend:80;
        proxy_set_header Host $host;
    }
}